server:
  enabled: true
  env:
    DB_HOST: "postgresql"
    DB_PORT: "5432"
    DB_NAME: "owlistic"
    DB_USER: "owlistic"
    DB_PASSWORD: "owlistic"
    BROKER_ADDRESS: "nats:4222"
  image:
    repository: ghcr.io/owlistic-notes/owlistic
    pullPolicy: IfNotPresent
    tag: "0.2.0"
  persistence:
    data:
      enabled: true
      size: 8Gi
      accessMode: ReadWriteOnce
      storageClassName: "-"
      # existingClaim: ""
  service:
    enabled: true
    type: ClusterIP
    port: 8080

app:
  enabled: true
  image:
    repository: ghcr.io/owlistic-notes/owlistic-app
    pullPolicy: IfNotPresent
    tag: "0.2.0"
  service:
    enabled: true
    type: ClusterIP
    port: 80

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: owlistic
        password: owlistic
        database: owlistic

nats:
  enabled: true
  nats:
    port: 4222
  jetstream:
    enabled: true
    fileStore:
      enabled: true
      dir: /data
      pvc:
        enabled: false
        size: 512Mi
        storageClassName: "-"
