server:
  enabled: true
  image:
    repository: ghrc.io/owlistic-notes/owlistic
    tag: "latest"
  service:
    enabled: true
    type: ClusterIP
    port: 8080
  persistence:
    data:
      enabled: true
      size: 8Gi
      accessMode: ReadWriteOnce
      storageClass: "-"
      existingClaim:
  env:
    DB_HOST: postgresql
    DB_PORT: 5432
    DB_NAME: owlistic
    DB_USER: owlistic
    DB_PASSWORD: owlistic
    KAFKA_BROKER: kafka:9092

app:
  enabled: true
  image:
    repository: ghrc.io/owlistic-notes/owlistic-app
    tag: "latest"
  service:
    enabled: true
    type: ClusterIP
    port: 80

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: owlistic
        password: owlistic
        database: owlistic

zookeeper:
  enabled: true

kafka:
  enabled: true
  extraEnvVars:
    - name: KAFKA_BROKER_ID
      value: "1"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper:2181
    - name: ALLOW_PLAINTEXT_LISTENER
      value: yes
    - name: KAFKA_ADVERTISED_LISTENERS
      value: PLAINTEXT://kafka:9092
    - name: KAFKA_LISTENERS
      value: PLAINTEXT://
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: PLAINTEXT:PLAINTEXT
